### ISSUE TITLE
Timestamps are not correct, maybe depending on system timezone

### ISSUE THREAD

**Issue by katylava** [sailrish/shipit#27]
The delivered timestamp for `61299998245242452033` is `2016-04-12T15:23:00.000Z` according to FedEx, but shipit converts it to `2016-04-12T10:23:00.000Z`. My timezone is -5 hours, and it's 5 hours off, so could be something to do with that.

**Comment by katylava** [comment]
Or maybe depending on where the FedEx activity occurred... that would make more sense.

**Comment by katylava** [comment]
The tests are wrong here: https://github.com/sailrish/shipit/blob/master/test/fedex.coffee#L154 – the test is validating `2014-02-17T09:05:00.000Z`, but the timestamp in the stub data is `2014-02-17T09:05:00-05:00`.

**Comment by sailrish** [comment]
Fixed in #29.
