### ISSUE TITLE
FedEx not guessed properly

### ISSUE THREAD

**Issue by bbodenmiller** [sailrish/shipit#33]
Looks like https://shipit-api.herokuapp.com/api/guess/1001910564210009250700663553999167 isn't properly guessing the number as FedEx:

https://www.fedex.com/apps/fedextrack/?tracknumbers=1001910564210009250700663553999167

**Comment by sailrish** [comment]
@bbodenmiller This doesn't look like a valid fedex tracking number. I tried to track it [here](https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber=1001910564210009250700663553999167&cntry_code=us&locale=en_US).

**Comment by bbodenmiller** [comment]
At the time it worked but looks like FedEx doesn't keep records forever.

**Comment by sailrish** [comment]
Please let me know if this is still a problem.
